# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Y19meHNZtr3J3X1AihUvKm+LANW1dnONYkFk3L1fbNiMqs/uXh+IpHSLau8vUhMq8l3A7M1VbSVUxM9/Kep4IOiVLA4bKUkmcGDJgfWrf5rypQF0lyq+IvzFd8cNywx++lvUc6PuT/r2iB793NTYWFj0Y+UCERN3m2fPwipRwuyQDy4uAjaUig7cn5j4nFcqGi7kEeIawIwp/IzSke9+563mM0lSyJxZtVFyL6rcNBdqergPuyWJXoutpYPCao84DxJzVg0EMYZjvCoqdwAh0Cm4Q8xPL0pHCkqSdZ2411bs4a7suYrm6qwuXDIOXTKWlw13W7kro40LqN6e6atRZFmXBaPeWtIZMZFP3lLNboyY5j5VsT2PqHIU2swySDAp3r4EQj257PEcQkC7pdCYssiXAbqAVZ+y2nEUQljPDPo3fJUALnNDg0Io9a7fZf6x7C9qV5mF8wRc/xDZRnnMdaKgf93+KDJ5hVXP8q7fqk9JaPi0SPdR6Hj0TU9S7DEKgm7uOjQTgZG9cO5/SEMQvZ89+CfGMktjJk/xtBsa17V5ZguFE4FMlaOyryEybbJwNqoquVCngJcYl6yg6/+LPTEyh9GI9G8jBtbG/0jqq/XG5xPR3pj0a7oTZArLYp0QeYhjfdSufo/DnEYM6m8qLglyydIVqxOH4woEPASOJjw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
