travis:
  secure:
    BINSTAR_TOKEN: rwfeJWIyFOY1tZW7EyExReWf3UgomOrEBfzHQEkcbY7RkNtBYpruA0k88BTCqB+4N0aYr+q9R1dT0Hkcjrk9QbekqD9xE5X9f7bJi86TfN+KWulD1fwJ1aZn4MbsyoVZ34LpGqhDG17hkc7ZyQ2yanAoz3IZNXDAJoDbXDNIFnUFIkQveDv+epDTA7xV7H/J9S7N6o1B4qNKvkgcMKIxgklPT0ExE9YfJx/5rORj6A2WzsLLHoGyYel+YrOtcKko3VbdCu4NAz6vwWUXKvntVeptMW/CqHOyOVEHQd+h5T7+utnXadxxWiBXa2Gcr7LPYLTmN5Gn4znxnrYjDPN33xFWAxgR4CzqT1UcHGkGEOd/JviwmNfJR9oZepx/61vbvDTscfHXP/ZGpBHkgWj2NEYSCaqTf7Ffke5y05nH2U+8sT6WzZnNZ5lSi2d5OSwkDsX2B1y1HvYovzQMmr3HRh2v7YVgpYldS1A5/Qutomvsqb+xVcREt1wbzvil75QDlqblpWY+jGML8uVDVu64YkhFux5+EkLZJFnc1fyt5WlaS8xQ+MI/e4hV0a48nrCCUQ5o/u4XABcZAVtRBchSMTonNLuwEOoKy/oeypRX05eZ5Ghbx4ZvUoiWwogl/17H6cbgDlWFuD9VjNGJA3RKBwBZs5CdjlP/eNc4F5YhGaY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
